const products = [
    {
        id: "nxksjkn3kjsd1",
        name: "Tinubu Fila",
        quantity: 20,
        categogy: "Fila",
        price: 14500,
        enabled: false,
        description: "A very good shirt.",
        size: "L",
        color: "White",
        trending: true,
        img: ["./img/fila.jpeg", "./img/logo_black.jpeg", "./img/logo_white.jpeg"]
    },
    {
        id: "prod002",
        name: "Royal Kaftan",
        quantity: 15,
        categogy: "Kaftan",
        price: 18500,
        enabled: true,
        description: "Premium royal kaftan with embroidery.",
        size: "XL",
        color: "Blue",
        trending: false,
        img: ["./img/fila.jpeg", "./img/logo_black.jpeg", "./img/logo_white.jpeg"]
    },
    {
        id: "prod003",
        name: "Vintage Denim",
        quantity: 25,
        categogy: "Vintage",
        price: 12000,
        enabled: true,
        description: "Classic vintage denim wear.",
        size: "M",
        color: "Navy",
        trending: false,
        img: ["./img/fila.jpeg", "./img/logo_black.jpeg", "./img/logo_white.jpeg"]
    },
    {
        id: "prod004",
        name: "Crew Neck Tee",
        quantity: 35,
        categogy: "Tees & Trousers",
        price: 8500,
        enabled: true,
        description: "Comfortable crew neck t-shirt.",
        size: "L",
        color: "Black",
        trending: false,
        img: ["./img/fila.jpeg", "./img/logo_black.jpeg", "./img/logo_white.jpeg"]
    },
    {
        id: "prod005",
        name: "Golden Fila",
        quantity: 18,
        categogy: "Fila",
        price: 16000,
        enabled: true,
        description: "Elegant fila with gold trim.",
        size: "XXL",
        color: "Gold",
        trending: false,
        img: ["./img/fila.jpeg", "./img/logo_black.jpeg", "./img/logo_white.jpeg"]
    },
    {
        id: "prod006",
        name: "Striped Kaftan",
        quantity: 12,
        categogy: "Kaftan",
        price: 17500,
        enabled: true,
        description: "Beautiful striped kaftan design.",
        size: "M",
        color: "Red",
        trending: false,
        img: ["./img/fila.jpeg", "./img/logo_black.jpeg", "./img/logo_white.jpeg"]
    },
    {
        id: "prod007",
        name: "Retro Vintage Shirt",
        quantity: 0,
        categogy: "Vintage",
        price: 11500,
        enabled: true,
        description: "Retro style vintage shirt.",
        size: "XL",
        color: "Brown",
        trending: false,
        img: ["./img/fila.jpeg", "./img/logo_black.jpeg", "./img/logo_white.jpeg"]
    },
    {
        id: "prod008",
        name: "Slim Fit Trousers",
        quantity: 28,
        categogy: "Tees & Trousers",
        price: 10500,
        enabled: true,
        description: "Comfortable slim fit trousers.",
        size: "L",
        color: "Gray",
        trending: false,
        img: ["./img/fila.jpeg", "./img/logo_black.jpeg", "./img/logo_white.jpeg"]
    },
    {
        id: "prod009",
        name: "Traditional Fila",
        quantity: 16,
        categogy: "Fila",
        price: 15000,
        enabled: true,
        description: "Traditional pattern fila.",
        size: "M",
        color: "Green",
        trending: false,
        img: ["./img/fila.jpeg", "./img/logo_black.jpeg", "./img/logo_white.jpeg"]
    },
    {
        id: "prod010",
        name: "Embroidered Kaftan",
        quantity: 14,
        categogy: "Kaftan",
        price: 19500,
        enabled: true,
        description: "Handembroidered kaftan.",
        size: "XXL",
        color: "Purple",
        trending: false,
        img: ["./img/fila.jpeg", "./img/logo_black.jpeg", "./img/logo_white.jpeg"]
    },
    {
        id: "prod011",
        name: "Faded Vintage",
        quantity: 30,
        categogy: "Vintage",
        price: 9800,
        enabled: true,
        description: "Faded vintage casual wear.",
        size: "L",
        color: "Beige",
        trending: false,
        img: ["./img/fila.jpeg", "./img/logo_black.jpeg", "./img/logo_white.jpeg"]
    },
    {
        id: "prod012",
        name: "V-Neck Tee",
        quantity: 32,
        categogy: "Tees & Trousers",
        price: 7500,
        enabled: true,
        description: "Stylish v-neck t-shirt.",
        size: "M",
        color: "White",
        trending: false,
        img: ["./img/fila.jpeg", "./img/logo_black.jpeg", "./img/logo_white.jpeg"]
    },
    {
        id: "prod013",
        name: "Silk Fila",
        quantity: 11,
        categogy: "Fila",
        price: 17500,
        enabled: true,
        description: "Premium silk fila.",
        size: "L",
        color: "Cream",
        trending: true,
        img: ["./img/fila.jpeg", "./img/logo_black.jpeg", "./img/logo_white.jpeg"]
    },
    {
        id: "prod014",
        name: "Desert Kaftan",
        quantity: 19,
        categogy: "Kaftan",
        price: 16000,
        enabled: true,
        description: "Desert inspired kaftan.",
        size: "XL",
        color: "Tan",
        trending: false,
        img: ["./img/fila.jpeg", "./img/logo_black.jpeg", "./img/logo_white.jpeg"]
    },
    {
        id: "prod015",
        name: "Classic Vintage",
        quantity: 26,
        categogy: "Vintage",
        price: 13500,
        enabled: true,
        description: "Classic vintage style wear.",
        size: "XXL",
        color: "Maroon",
        trending: false,
        img: ["./img/fila.jpeg", "./img/logo_black.jpeg", "./img/logo_white.jpeg"]
    },
    {
        id: "prod016",
        name: "Chino Trousers",
        quantity: 24,
        categogy: "Tees & Trousers",
        price: 11000,
        enabled: true,
        description: "Premium chino trousers.",
        size: "L",
        color: "Khaki",
        trending: false,
        img: ["./img/fila.jpeg", "./img/logo_black.jpeg", "./img/logo_white.jpeg"]
    },
    {
        id: "prod017",
        name: "Wax Print Fila",
        quantity: 13,
        categogy: "Fila",
        price: 15500,
        enabled: true,
        description: "Vibrant wax print fila.",
        size: "M",
        color: "Orange",
        trending: false,
        img: ["./img/fila.jpeg", "./img/logo_black.jpeg", "./img/logo_white.jpeg"]
    },
    {
        id: "prod018",
        name: "Linen Kaftan",
        quantity: 17,
        categogy: "Kaftan",
        price: 18000,
        enabled: true,
        description: "Breathable linen kaftan.",
        size: "L",
        color: "Ivory",
        trending: false,
        img: ["./img/fila.jpeg", "./img/logo_black.jpeg", "./img/logo_white.jpeg"]
    },
    {
        id: "prod019",
        name: "Distressed Vintage",
        quantity: 29,
        categogy: "Vintage",
        price: 10200,
        enabled: true,
        description: "Trendy distressed vintage wear.",
        size: "XL",
        color: "Black",
        trending: false,
        img: ["./img/fila.jpeg", "./img/logo_black.jpeg", "./img/logo_white.jpeg"]
    },
    {
        id: "prod020",
        name: "Cargo Trousers",
        quantity: 21,
        categogy: "Tees & Trousers",
        price: 12500,
        enabled: true,
        description: "Functional cargo trousers.",
        size: "XXL",
        color: "Olive",
        trending: false,
        img: ["./img/fila.jpeg", "./img/logo_black.jpeg", "./img/logo_white.jpeg"]
    },
    {
        id: "prod021",
        name: "Kente Fila",
        quantity: 10,
        categogy: "Fila",
        price: 16500,
        enabled: true,
        description: "Traditional kente fila.",
        size: "XL",
        color: "Multi-color",
        trending: true,
        img: ["./img/fila.jpeg", "./img/logo_black.jpeg", "./img/logo_white.jpeg"]
    }
]
// ["M", "L", "XL", "XXL"]
// [fila, vintage, "tees & trousers", kaftan]